services:
  web:
    build: .
    ports:
      - "3113:3113"
    depends_on:
      - redis
      - mongo
  redis:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"
  mongo:
    container_name: mongo-server
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
