services:
  web:
    container_name: articard
    build: .
    ports:
      - "3113:3113"
    environment:
      - TELP_PORT=3113
      - TELP_RIJKSMUSEUM_API_KEY=
      - TELP_RIJKSMUSEUM_USER_ID=
      - TELP_RIJKSMUSEUM_USERSET_NAME=
      - TELP_RIJKSMUSEUM_BASE_USERSETS_URL=https://www.rijksmuseum.nl/api/en/usersets
      - TELP_RIJKSMUSEUM_BASE_COLLECTION_URL=https://www.rijksmuseum.nl/api/en/collection
      - TELP_DATABASE_URL=mongodb://mongo-server:27017/telp
      - TELP_REDIS_URL=redis://redis-server:6379
      - TELP_HOST=
    depends_on:
      - redis
      - mongo
  redis:
    container_name: redis-server
    image: redis
    ports:
      - "6379:6379"
  mongo:
    container_name: mongo-server
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
